### ISSUE TITLE
Save Hotkey

### ISSUE THREAD

**Issue by SoulKa** [EXXETA/trufos#161]
It would be helpful to use CMD + S (CTLR + S) to save changes of the currently opened request, just as the save button does.

## Acceptance Criteria
- On OSX: CMD + S saves the currently opened request
- On Windows: CTLR + S saves the currently opened request

**Comment by vicky16898** [comment]
I will work on this.

**Comment by vicky16898** [comment]
Is there an existing save functionality? I attempted to create new requests but was unable to locate a save button.
![image](https://github.com/user-attachments/assets/649cf079-ab35-4dc3-98c7-a0137df32fd0)

**Comment by SoulKa** [comment]
Yes there's already a save button, but it's easy to overlook. It's located inside the URL input:
![image](https://github.com/user-attachments/assets/6043e5c6-c432-46ee-882f-4187ff81e7cc)

You can see the save code being called in https://github.com/EXXETA/trufos/blob/cdc9f11d650bfa9d3a4bdfb93724878a3d74eec5/src/renderer/components/mainWindow/MainTopBar.tsx#L52-L64.

**Comment by vicky16898** [comment]
Oh yeah. Now I can save the requests. Thanks for pointing it out. Thanks for showing me the save code logic as well.

**Comment by vicky16898** [comment]
I have raised a PR for this issue,
https://github.com/EXXETA/trufos/pull/169

**Comment by vicky16898** [comment]
I have raised a PR for this issue but the pipeline fails because of the following error,
**Pull request is invalid.**
This is due to missing issue reference in the PR but I have mentioned it using the keywords and I tried editing the description as well.
