### ISSUE TITLE
Disable CI on Draft PRs

### ISSUE THREAD

**Issue by SoulKa** [EXXETA/trufos#167]
Currently, pipelines are also running if a PR is a draft. This wastes unnecessary worker minutes (and also energy). It's possible to disable pipeline triggering for draft PRs.

**Comment by vicky16898** [comment]
I am working on this issue.
can you check this PR?
https://github.com/EXXETA/trufos/pull/168. 
I think you will have to approve the workflows for the pipelines to run.
The **PR is in draft mode** so the pipelines shouldn't run.
